### ISSUE TITLE
Find a bug in the existing version of project

### ISSUE THREAD

**Issue by kaiiyer** [kaiiyer/UBA#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shibam17** [comment]
Hey, I would like to take up this issue. Is it available? (Participant of GSSoC'20)

**Comment by kaiiyer** [comment]
Yeah Sure !!

**Comment by shibam17** [comment]
**BUG**- The Interface websites are not responsive properly(FOOTER), when the screen is shifted to smaller pixel, the footer elements are no longer accessible. The elements should be visible as a drop-down list plus the button should be aligned to any corner.

To Reproduce/Check:
1.Go to UBA/interface/html
2. Click on any html file(anomalise/cases/D3Graph/data/index/modeling)
3.Press Ctrl+Shift+i
4.Switch views (mobile, tablet, etc.)
5.Observe the footer elements.

**Expected Behavior**
In the mobile view, all the footer elements should be visible as a drop down when clicked and the button for element should be aligned to one corner.

**Screenshot**
![image](https://user-images.githubusercontent.com/56026147/75466812-c310dd80-59b0-11ea-9563-0e00c139da1d.png)

**Comment by Jovonni** [comment]
This isn’t a bug, as the UI being responsive wasn’t in scope at first. It’s more of a feature request. Feel free to create a PR and correct it though.

**Comment by kaiiyer** [comment]
I'll just add Responsive UI as a feature request so that the interested may work on it !!

**Comment by kaiiyer** [comment]
Check out [this](https://github.com/kaiiyer/UBA/issues/25)
@soulhunter10737

**Comment by shibam17** [comment]
Okay, I understood. Will it(idea) be counted in any aspect? Thank you!
